Repository np-devops-team1/DevOps_Main, pull requests merged in 2022-02, with the labels that each got.

#45 Feat/building pool
  main.py
Labels: Scrum

#46 feat: add calculate score board
  main.py
Labels: Dev

#48 ci: create workflow to alert telegram on release
  .github/workflows/Release.yaml
Labels: QA

#47 feat/add see current score and print score all
  main.py
Labels: enhancement, Dev

#49 Feat/save game
  .gitignore
  main.py
Labels: enhancement, Dev

#52 fix: breakdown score calculation for prk
  main.py
Labels: Dev

#53 Feat/high score
  main.py
Labels: Scrum

#54 fix: add score key value to see_current_score
  main.py
Labels: Dev
