Repository np-devops-team1/DevOps_Main, pull requests merged in 2022-01, with the labels that each got.

#11 Issue/10 bug
  .gitignore
  __pycache__/main.cpython-37.pyc
  main.py
Labels: bug

#21 ci/pull request label workflow
  .github/teams.yml
  .github/workflows/Label_PR.yml
Labels: documentation, QA

#23 fix/remove sample test file
  sample_test.py
Labels: QA

#19 feat: add func to plot building
  main.py
Labels: Dev

#18 Feat/start new game
  .vscode/settings.json
  main.py
Labels: Dev

#25 feat: save ongoing game
  main.py
Labels: Dev

#26 Feat/score adjacent buildings
  .coverage
  main.py
Labels: Dev

#24 ci/deployment workflow
  .github/workflows/Deployment.yml
Labels: enhancement, QA

#30 ci: integrate SeriesCI API to monitor test results
  .github/workflows/CI_QA.yml
  conftest.py
Labels: QA

#32 ci: change workflow trigger conditions
  .github/workflows/CI_QA.yml
Labels: QA

#33 Ci/ci dev changes
  .github/workflows/CI_Dev.yml
Labels: Dev

#34 Ci/dev workflow update
  .github/workflows/CI_Dev.yml
  README.md
Labels: Dev

#35 ref: updated code to fit refactored test script
  .github/workflows/CI_Dev.yml
  main.py
Labels: enhancement, Dev

#37 feat: add size selection feature
  main.py
Labels: Dev

#38 Feat/init new game data
  .github/workflows/CI_Dev.yml
  main.py
Labels: Scrum

#39 feat: start new game
  main.py
Labels: Scrum

#40 Feat/game menu
  main.py
Labels: Scrum

#42 Fix for QA compliance
  main.py
Labels: Scrum

#43 Feat/select building location
  main.py
Labels: Dev, Scrum

#44 Feat/build building
  main.py
Labels: enhancement, Dev
